/* tslint:disable */
/* eslint-disable */
/**
 * 决定proto引用路径和rpc路由
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BatchJobBaseInfoA } from "./batch-job-base-info-a";
/**
 *
 *
 * @export
 * @interface BatchJobQueryJobListRsp
 */
export interface BatchJobQueryJobListRsp {
  /**
   * @type {number}
   * @memberof BatchJobQueryJobListRsp
   */
  total?: number;

  /**
   * @type {number}
   * @memberof BatchJobQueryJobListRsp
   */
  pageSize?: number;

  /**
   * @type {Array<BatchJobBaseInfoA>}
   * @memberof BatchJobQueryJobListRsp
   */
  line?: Array<BatchJobBaseInfoA>;
}
