/* tslint:disable */
/* eslint-disable */
/**
 * 决定proto引用路径和rpc路由
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * - Debug: 调试  - Info: 信息  - Warn: 警告  - Err: 错误
 * @export
 * @enum {string}
 */
export enum BatchJobDataLogType {
  Debug = "Debug",
  Info = "Info",
  Warn = "Warn",
  Err = "Err"
}
