/* tslint:disable */
/* eslint-disable */
/**
 * 决定proto引用路径和rpc路由
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BatchJobBizStatus } from "./batch-job-biz-status";
import { BatchJobExecType } from "./batch-job-exec-type";
import { BatchJobOpInfoA } from "./batch-job-op-info-a";
/**
 *
 *
 * @export
 * @interface BatchJobBizInfoByListA
 */
export interface BatchJobBizInfoByListA {
  /**
   * @type {number}
   * @memberof BatchJobBizInfoByListA
   */
  bizId?: number;

  /**
   * @type {string}
   * @memberof BatchJobBizInfoByListA
   */
  bizName?: string;

  /**
   * @type {string}
   * @memberof BatchJobBizInfoByListA
   */
  remark?: string;

  /**
   * @type {BatchJobExecType}
   * @memberof BatchJobBizInfoByListA
   */
  execType?: BatchJobExecType;

  /**
   * @type {BatchJobOpInfoA}
   * @memberof BatchJobBizInfoByListA
   */
  op?: BatchJobOpInfoA;

  /**
   * @type {BatchJobBizStatus}
   * @memberof BatchJobBizInfoByListA
   */
  status?: BatchJobBizStatus;
}
