/* tslint:disable */
/* eslint-disable */
/**
 * 决定proto引用路径和rpc路由
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BatchJobDataLogType } from "./batch-job-data-log-type";
/**
 *
 *
 * @export
 * @interface BatchJobDataLogQ
 */
export interface BatchJobDataLogQ {
  /**
   * @type {string}
   * @memberof BatchJobDataLogQ
   */
  dataId?: string;

  /**
   * @type {string}
   * @memberof BatchJobDataLogQ
   */
  remark?: string;

  /**
   * @type {string}
   * @memberof BatchJobDataLogQ
   */
  extend?: string;

  /**
   * @type {BatchJobDataLogType}
   * @memberof BatchJobDataLogQ
   */
  logType?: BatchJobDataLogType;
}
