/* tslint:disable */
/* eslint-disable */
/**
 * 决定proto引用路径和rpc路由
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BatchJobDataLogType } from "./batch-job-data-log-type";
/**
 *
 *
 * @export
 * @interface BatchJobQueryJobDataLogReq
 */
export interface BatchJobQueryJobDataLogReq {
  /**
   * @type {string}
   * @memberof BatchJobQueryJobDataLogReq
   */
  jobId?: string;

  /**
   * @type {string}
   * @memberof BatchJobQueryJobDataLogReq
   */
  nextCursor?: string;

  /**
   * @type {number}
   * @memberof BatchJobQueryJobDataLogReq
   */
  pageSize?: number;

  /**
   * @type {string}
   * @memberof BatchJobQueryJobDataLogReq
   */
  startTime?: string;

  /**
   * @type {string}
   * @memberof BatchJobQueryJobDataLogReq
   */
  endTime?: string;

  /**
   * @type {Array<BatchJobDataLogType>}
   * @memberof BatchJobQueryJobDataLogReq
   */
  logType?: Array<BatchJobDataLogType>;
}
