/* tslint:disable */
/* eslint-disable */
/**
 * 决定proto引用路径和rpc路由
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BatchJobBizInfoByListA } from "./batch-job-biz-info-by-list-a";
/**
 *
 *
 * @export
 * @interface BatchJobQueryBizListRsp
 */
export interface BatchJobQueryBizListRsp {
  /**
   * @type {number}
   * @memberof BatchJobQueryBizListRsp
   */
  total?: number;

  /**
   * @type {number}
   * @memberof BatchJobQueryBizListRsp
   */
  pageSize?: number;

  /**
   * @type {Array<BatchJobBizInfoByListA>}
   * @memberof BatchJobQueryBizListRsp
   */
  line?: Array<BatchJobBizInfoByListA>;
}
