/* tslint:disable */
/* eslint-disable */
/**
 * 决定proto引用路径和rpc路由
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BatchJobDataLogA } from "./batch-job-data-log-a";
/**
 *
 *
 * @export
 * @interface BatchJobQueryJobDataLogRsp
 */
export interface BatchJobQueryJobDataLogRsp {
  /**
   * @type {number}
   * @memberof BatchJobQueryJobDataLogRsp
   */
  total?: number;

  /**
   * @type {number}
   * @memberof BatchJobQueryJobDataLogRsp
   */
  pageSize?: number;

  /**
   * @type {Array<BatchJobDataLogA>}
   * @memberof BatchJobQueryJobDataLogRsp
   */
  log?: Array<BatchJobDataLogA>;
}
