/* tslint:disable */
/* eslint-disable */
/**
 * 决定proto引用路径和rpc路由
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * - RateSec: 标准限速  - Serialization: 串行化限速
 * @export
 * @enum {string}
 */
export enum BatchJobRateType {
  RateSec = "RateSec",
  Serialization = "Serialization"
}
