/* tslint:disable */
/* eslint-disable */
/**
 * 决定proto引用路径和rpc路由
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { QueryAllBizNameRspLineA } from "./query-all-biz-name-rsp-line-a";
/**
 *
 *
 * @export
 * @interface BatchJobQueryAllBizNameRsp
 */
export interface BatchJobQueryAllBizNameRsp {
  /**
   * @type {Array<QueryAllBizNameRspLineA>}
   * @memberof BatchJobQueryAllBizNameRsp
   */
  line?: Array<QueryAllBizNameRspLineA>;
}
