/* tslint:disable */
/* eslint-disable */
/**
 * 决定proto引用路径和rpc路由
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface BatchJobBizUpdateJobDataReq
 */
export interface BatchJobBizUpdateJobDataReq {
  /**
   * @type {string}
   * @memberof BatchJobBizUpdateJobDataReq
   */
  authCode?: string;

  /**
   * @type {string}
   * @memberof BatchJobBizUpdateJobDataReq
   */
  jobId?: string;

  /**
   * @type {string}
   * @memberof BatchJobBizUpdateJobDataReq
   */
  jobData?: string;

  /**
   * @type {string}
   * @memberof BatchJobBizUpdateJobDataReq
   */
  processDataTotal?: string;

  /**
   * @type {string}
   * @memberof BatchJobBizUpdateJobDataReq
   */
  processedCount?: string;

  /**
   * @type {string}
   * @memberof BatchJobBizUpdateJobDataReq
   */
  remark?: string;
}
