/* tslint:disable */
/* eslint-disable */
/**
 * 决定proto引用路径和rpc路由
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BatchJobBizStatus } from "./batch-job-biz-status";
import { BatchJobExecExtendDataA } from "./batch-job-exec-extend-data-a";
import { BatchJobExecType } from "./batch-job-exec-type";
import { BatchJobOpInfoA } from "./batch-job-op-info-a";
/**
 *
 *
 * @export
 * @interface BatchJobBizInfoA
 */
export interface BatchJobBizInfoA {
  /**
   * @type {number}
   * @memberof BatchJobBizInfoA
   */
  bizId?: number;

  /**
   * @type {string}
   * @memberof BatchJobBizInfoA
   */
  bizName?: string;

  /**
   * @type {string}
   * @memberof BatchJobBizInfoA
   */
  remark?: string;

  /**
   * @type {BatchJobExecType}
   * @memberof BatchJobBizInfoA
   */
  execType?: BatchJobExecType;

  /**
   * @type {BatchJobExecExtendDataA}
   * @memberof BatchJobBizInfoA
   */
  execExtendData?: BatchJobExecExtendDataA;

  /**
   * @type {BatchJobOpInfoA}
   * @memberof BatchJobBizInfoA
   */
  op?: BatchJobOpInfoA;

  /**
   * @type {BatchJobBizStatus}
   * @memberof BatchJobBizInfoA
   */
  status?: BatchJobBizStatus;

  /**
   * @type {string}
   * @memberof BatchJobBizInfoA
   */
  createTime?: string;
}
