/* tslint:disable */
/* eslint-disable */
/**
 * 决定proto引用路径和rpc路由
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BatchJobBizStatus } from "./batch-job-biz-status";
import { BatchJobExecType } from "./batch-job-exec-type";
import { BatchJobOpInfoQ } from "./batch-job-op-info-q";
/**
 *
 *
 * @export
 * @interface BatchJobAdminChangeBizReq
 */
export interface BatchJobAdminChangeBizReq {
  /**
   * @type {number}
   * @memberof BatchJobAdminChangeBizReq
   */
  bizId?: number;

  /**
   * @type {string}
   * @memberof BatchJobAdminChangeBizReq
   */
  bizName?: string;

  /**
   * @type {string}
   * @memberof BatchJobAdminChangeBizReq
   */
  remark?: string;

  /**
   * @type {BatchJobExecType}
   * @memberof BatchJobAdminChangeBizReq
   */
  execType?: BatchJobExecType;

  /**
   * @type {string}
   * @memberof BatchJobAdminChangeBizReq
   */
  cbBeforeCreate?: string;

  /**
   * @type {string}
   * @memberof BatchJobAdminChangeBizReq
   */
  cbBeforeRun?: string;

  /**
   * @type {string}
   * @memberof BatchJobAdminChangeBizReq
   */
  cbProcess?: string;

  /**
   * @type {string}
   * @memberof BatchJobAdminChangeBizReq
   */
  cbProcessStop?: string;

  /**
   * @type {number}
   * @memberof BatchJobAdminChangeBizReq
   */
  cbBeforeCreateTimeout?: number;

  /**
   * @type {number}
   * @memberof BatchJobAdminChangeBizReq
   */
  cbBeforeRunTimeout?: number;

  /**
   * @type {number}
   * @memberof BatchJobAdminChangeBizReq
   */
  cbProcessTimeout?: number;

  /**
   * @type {number}
   * @memberof BatchJobAdminChangeBizReq
   */
  cbProcessStopTimeout?: number;

  /**
   * @type {BatchJobOpInfoQ}
   * @memberof BatchJobAdminChangeBizReq
   */
  op?: BatchJobOpInfoQ;

  /**
   * @type {BatchJobBizStatus}
   * @memberof BatchJobAdminChangeBizReq
   */
  status?: BatchJobBizStatus;
}
