/* tslint:disable */
/* eslint-disable */
/**
 * 决定proto引用路径和rpc路由
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BatchJobOpInfoQ } from "./batch-job-op-info-q";
/**
 *
 *
 * @export
 * @interface BatchJobAdminStartJobReq
 */
export interface BatchJobAdminStartJobReq {
  /**
   * @type {string}
   * @memberof BatchJobAdminStartJobReq
   */
  jobId?: string;

  /**
   * @type {BatchJobOpInfoQ}
   * @memberof BatchJobAdminStartJobReq
   */
  op?: BatchJobOpInfoQ;
}
