/* tslint:disable */
/* eslint-disable */
/**
 * 决定proto引用路径和rpc路由
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface BatchJobQueryJobListReq
 */
export interface BatchJobQueryJobListReq {
  /**
   * @type {string}
   * @memberof BatchJobQueryJobListReq
   */
  startTime?: string;

  /**
   * @type {string}
   * @memberof BatchJobQueryJobListReq
   */
  endTime?: string;

  /**
   * @type {string}
   * @memberof BatchJobQueryJobListReq
   */
  opUser?: string;

  /**
   * @type {Array<number>}
   * @memberof BatchJobQueryJobListReq
   */
  bizType?: Array<number>;

  /**
   * @type {number}
   * @memberof BatchJobQueryJobListReq
   */
  page?: number;

  /**
   * @type {number}
   * @memberof BatchJobQueryJobListReq
   */
  pageSize?: number;
}
