/* tslint:disable */
/* eslint-disable */
/**
 * 决定proto引用路径和rpc路由
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BatchJobKV } from "./batch-job-kv";
/**
 *
 *
 * @export
 * @interface BatchJobExecExtendDataHttpCallbackA
 */
export interface BatchJobExecExtendDataHttpCallbackA {
  /**
   * @type {string}
   * @memberof BatchJobExecExtendDataHttpCallbackA
   */
  beforeCreate?: string;

  /**
   * @type {string}
   * @memberof BatchJobExecExtendDataHttpCallbackA
   */
  beforeRun?: string;

  /**
   * @type {string}
   * @memberof BatchJobExecExtendDataHttpCallbackA
   */
  process?: string;

  /**
   * @type {string}
   * @memberof BatchJobExecExtendDataHttpCallbackA
   */
  processStop?: string;

  /**
   * @type {number}
   * @memberof BatchJobExecExtendDataHttpCallbackA
   */
  beforeCreateTimeout?: number;

  /**
   * @type {number}
   * @memberof BatchJobExecExtendDataHttpCallbackA
   */
  beforeRunTimeout?: number;

  /**
   * @type {number}
   * @memberof BatchJobExecExtendDataHttpCallbackA
   */
  processTimeout?: number;

  /**
   * @type {number}
   * @memberof BatchJobExecExtendDataHttpCallbackA
   */
  processStopTimeout?: number;

  /**
   * @type {boolean}
   * @memberof BatchJobExecExtendDataHttpCallbackA
   */
  insecureSkipVerify?: boolean;

  /**
   * @type {Array<BatchJobKV>}
   * @memberof BatchJobExecExtendDataHttpCallbackA
   */
  headers?: Array<BatchJobKV>;

  /**
   * @type {string}
   * @memberof BatchJobExecExtendDataHttpCallbackA
   */
  proxy?: string;

  /**
   * @type {string}
   * @memberof BatchJobExecExtendDataHttpCallbackA
   */
  rspParseField?: string;
}
