/* tslint:disable */
/* eslint-disable */
/**
 * 决定proto引用路径和rpc路由
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * - DataLogType_Debug: 调试  - DataLogType_Info: 信息  - DataLogType_Warn: 警告  - DataLogType_Err: 错误
 * @export
 * @enum {string}
 */
export enum BatchJobDataLogType {
  Debug = "DataLogType_Debug",
  Info = "DataLogType_Info",
  Warn = "DataLogType_Warn",
  Err = "DataLogType_Err"
}
