/* tslint:disable */
/* eslint-disable */
/**
 * 决定proto引用路径和rpc路由
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface BatchJobExecExtendDataHttpCallbackQ
 */
export interface BatchJobExecExtendDataHttpCallbackQ {
  /**
   * @type {string}
   * @memberof BatchJobExecExtendDataHttpCallbackQ
   */
  cbBeforeCreate?: string;

  /**
   * @type {string}
   * @memberof BatchJobExecExtendDataHttpCallbackQ
   */
  cbBeforeRun?: string;

  /**
   * @type {string}
   * @memberof BatchJobExecExtendDataHttpCallbackQ
   */
  cbProcess?: string;

  /**
   * @type {string}
   * @memberof BatchJobExecExtendDataHttpCallbackQ
   */
  cbProcessStop?: string;

  /**
   * @type {number}
   * @memberof BatchJobExecExtendDataHttpCallbackQ
   */
  cbBeforeCreateTimeout?: number;

  /**
   * @type {number}
   * @memberof BatchJobExecExtendDataHttpCallbackQ
   */
  cbBeforeRunTimeout?: number;

  /**
   * @type {number}
   * @memberof BatchJobExecExtendDataHttpCallbackQ
   */
  cbProcessTimeout?: number;

  /**
   * @type {number}
   * @memberof BatchJobExecExtendDataHttpCallbackQ
   */
  cbProcessStopTimeout?: number;
}
