/* tslint:disable */
/* eslint-disable */
/**
 * 决定proto引用路径和rpc路由
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BatchJobExecType } from "./batch-job-exec-type";
import { BatchJobRateType } from "./batch-job-rate-type";
/**
 *
 *
 * @export
 * @interface BatchJobAdminRegistryBizReq
 */
export interface BatchJobAdminRegistryBizReq {
  /**
   * @type {number}
   * @memberof BatchJobAdminRegistryBizReq
   */
  bizType?: number;

  /**
   * @type {string}
   * @memberof BatchJobAdminRegistryBizReq
   */
  bizName?: string;

  /**
   * @type {string}
   * @memberof BatchJobAdminRegistryBizReq
   */
  remark?: string;

  /**
   * @type {BatchJobExecType}
   * @memberof BatchJobAdminRegistryBizReq
   */
  execType?: BatchJobExecType;

  /**
   * @type {string}
   * @memberof BatchJobAdminRegistryBizReq
   */
  cbBeforeCreate?: string;

  /**
   * @type {string}
   * @memberof BatchJobAdminRegistryBizReq
   */
  cbBeforeRun?: string;

  /**
   * @type {string}
   * @memberof BatchJobAdminRegistryBizReq
   */
  cbProcess?: string;

  /**
   * @type {string}
   * @memberof BatchJobAdminRegistryBizReq
   */
  cbProcessStop?: string;

  /**
   * @type {number}
   * @memberof BatchJobAdminRegistryBizReq
   */
  cbBeforeCreateTimeout?: number;

  /**
   * @type {number}
   * @memberof BatchJobAdminRegistryBizReq
   */
  cbBeforeRunTimeout?: number;

  /**
   * @type {number}
   * @memberof BatchJobAdminRegistryBizReq
   */
  cbProcessTimeout?: number;

  /**
   * @type {number}
   * @memberof BatchJobAdminRegistryBizReq
   */
  cbProcessStopTimeout?: number;

  /**
   * @type {BatchJobRateType}
   * @memberof BatchJobAdminRegistryBizReq
   */
  rateType?: BatchJobRateType;

  /**
   * @type {number}
   * @memberof BatchJobAdminRegistryBizReq
   */
  rateSec?: number;
}
