/* tslint:disable */
/* eslint-disable */
/**
 * 决定proto引用路径和rpc路由
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BatchJobJobStatus } from "./batch-job-job-status";
import { BatchJobOpInfoA } from "./batch-job-op-info-a";
/**
 *
 *
 * @export
 * @interface BatchJobJobStateInfo
 */
export interface BatchJobJobStateInfo {
  /**
   * @type {string}
   * @memberof BatchJobJobStateInfo
   */
  jobId?: string;

  /**
   * @type {string}
   * @memberof BatchJobJobStateInfo
   */
  processDataTotal?: string;

  /**
   * @type {string}
   * @memberof BatchJobJobStateInfo
   */
  processedCount?: string;

  /**
   * @type {string}
   * @memberof BatchJobJobStateInfo
   */
  errLogCount?: string;

  /**
   * @type {BatchJobJobStatus}
   * @memberof BatchJobJobStateInfo
   */
  status?: BatchJobJobStatus;

  /**
   * @type {BatchJobOpInfoA}
   * @memberof BatchJobJobStateInfo
   */
  op?: BatchJobOpInfoA;

  /**
   * @type {string}
   * @memberof BatchJobJobStateInfo
   */
  statusInfo?: string;
}
