/* tslint:disable */
/* eslint-disable */
/**
 * 决定proto引用路径和rpc路由
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface BatchJobBizUpdateBizDataReq
 */
export interface BatchJobBizUpdateBizDataReq {
  /**
   * @type {string}
   * @memberof BatchJobBizUpdateBizDataReq
   */
  jobId?: string;

  /**
   * @type {string}
   * @memberof BatchJobBizUpdateBizDataReq
   */
  bizData?: string;

  /**
   * @type {string}
   * @memberof BatchJobBizUpdateBizDataReq
   */
  bizProcessData?: string;

  /**
   * @type {string}
   * @memberof BatchJobBizUpdateBizDataReq
   */
  processDataTotal?: string;

  /**
   * @type {string}
   * @memberof BatchJobBizUpdateBizDataReq
   */
  processedNum?: string;
}
