/* tslint:disable */
/* eslint-disable */
/**
 * 决定proto引用路径和rpc路由
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface BatchJobQueryJobInfoReq
 */
export interface BatchJobQueryJobInfoReq {
  /**
   * @type {string}
   * @memberof BatchJobQueryJobInfoReq
   */
  jobId?: string;
}
