/* tslint:disable */
/* eslint-disable */
/**
 * 决定proto引用路径和rpc路由
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * - Created: 已创建  - WaitBizRun: 等待业务主动启动  - Running: 运行中  - Finished: 已完成  - Stopping: 正在停止  - Stopped: 已停止
 * @export
 * @enum {string}
 */
export enum BatchJobJobStatus {
  Created = "Created",
  WaitBizRun = "WaitBizRun",
  Running = "Running",
  Finished = "Finished",
  Stopping = "Stopping",
  Stopped = "Stopped"
}
