/* tslint:disable */
/* eslint-disable */
/**
 * 决定proto引用路径和rpc路由
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BatchJobConcType } from "./batch-job-conc-type";
import { BatchJobOpInfoQ } from "./batch-job-op-info-q";
/**
 *
 *
 * @export
 * @interface BatchJobAdminCreateJobReq
 */
export interface BatchJobAdminCreateJobReq {
  /**
   * @type {number}
   * @memberof BatchJobAdminCreateJobReq
   */
  bizId?: number;

  /**
   * @type {string}
   * @memberof BatchJobAdminCreateJobReq
   */
  jobName?: string;

  /**
   * @type {string}
   * @memberof BatchJobAdminCreateJobReq
   */
  jobData?: string;

  /**
   * @type {string}
   * @memberof BatchJobAdminCreateJobReq
   */
  processDataTotal?: string;

  /**
   * @type {string}
   * @memberof BatchJobAdminCreateJobReq
   */
  processedCount?: string;

  /**
   * @type {BatchJobConcType}
   * @memberof BatchJobAdminCreateJobReq
   */
  concType?: BatchJobConcType;

  /**
   * @type {number}
   * @memberof BatchJobAdminCreateJobReq
   */
  rateSec?: number;

  /**
   * @type {BatchJobOpInfoQ}
   * @memberof BatchJobAdminCreateJobReq
   */
  op?: BatchJobOpInfoQ;

  /**
   * @type {boolean}
   * @memberof BatchJobAdminCreateJobReq
   */
  startNow?: boolean;

  /**
   * @type {boolean}
   * @memberof BatchJobAdminCreateJobReq
   */
  processorCarryJobData?: boolean;
}
