/* tslint:disable */
/* eslint-disable */
/**
 * 决定proto引用路径和rpc路由
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * - JobStatusQ_All: 所有状态  - JobStatusQ_Created: 待启动: 已创建/已停止  - JobStatusQ_Running: 运行中: 运行中/等待业务主动启动/正在停止  - JobStatusQ_Finished: 已完成
 * @export
 * @enum {string}
 */
export enum BatchJobJobStatusQ {
  All = "JobStatusQ_All",
  Created = "JobStatusQ_Created",
  Running = "JobStatusQ_Running",
  Finished = "JobStatusQ_Finished"
}
