/* tslint:disable */
/* eslint-disable */
/**
 * 决定proto引用路径和rpc路由
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * - BizStatus_None: 正常  - BizStatus_Hidden: 隐藏
 * @export
 * @enum {string}
 */
export enum BatchJobBizStatus {
  None = "BizStatus_None",
  Hidden = "BizStatus_Hidden"
}
