/* tslint:disable */
/* eslint-disable */
/**
 * 决定proto引用路径和rpc路由
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BatchJobJobStatus } from "./batch-job-job-status";
import { BatchJobOpInfoA } from "./batch-job-op-info-a";
import { BatchJobRateType } from "./batch-job-rate-type";
/**
 *
 *
 * @export
 * @interface BatchJobJobInfoA
 */
export interface BatchJobJobInfoA {
  /**
   * @type {string}
   * @memberof BatchJobJobInfoA
   */
  jobId?: string;

  /**
   * @type {string}
   * @memberof BatchJobJobInfoA
   */
  jobName?: string;

  /**
   * @type {number}
   * @memberof BatchJobJobInfoA
   */
  bizId?: number;

  /**
   * @type {string}
   * @memberof BatchJobJobInfoA
   */
  jobData?: string;

  /**
   * @type {string}
   * @memberof BatchJobJobInfoA
   */
  processDataTotal?: string;

  /**
   * @type {string}
   * @memberof BatchJobJobInfoA
   */
  processedCount?: string;

  /**
   * @type {string}
   * @memberof BatchJobJobInfoA
   */
  errLogCount?: string;

  /**
   * @type {BatchJobJobStatus}
   * @memberof BatchJobJobInfoA
   */
  status?: BatchJobJobStatus;

  /**
   * @type {string}
   * @memberof BatchJobJobInfoA
   */
  createTime?: string;

  /**
   * @type {BatchJobRateType}
   * @memberof BatchJobJobInfoA
   */
  rateType?: BatchJobRateType;

  /**
   * @type {number}
   * @memberof BatchJobJobInfoA
   */
  rateSec?: number;

  /**
   * @type {BatchJobOpInfoA}
   * @memberof BatchJobJobInfoA
   */
  op?: BatchJobOpInfoA;

  /**
   * @type {string}
   * @memberof BatchJobJobInfoA
   */
  statusInfo?: string;
}
