/* tslint:disable */
/* eslint-disable */
/**
 * 决定proto引用路径和rpc路由
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BatchJobBizStatus } from "./batch-job-biz-status";
/**
 *
 *
 * @export
 * @interface QueryAllBizNameRspLineA
 */
export interface QueryAllBizNameRspLineA {
  /**
   * @type {number}
   * @memberof QueryAllBizNameRspLineA
   */
  bizType?: number;

  /**
   * @type {string}
   * @memberof QueryAllBizNameRspLineA
   */
  bizName?: string;

  /**
   * @type {BatchJobBizStatus}
   * @memberof QueryAllBizNameRspLineA
   */
  status?: BatchJobBizStatus;
}
